CadetCorps/Areas/SecurityGuard/Models/GrantRolesToUserViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;

namespace SecurityGuard.ViewModels
{
    public class GrantRolesToUserViewModel
    {
        public MembershipUser User { get; set; }
        public string UserName { get; set; }
        public SelectList AvailableRoles { get; set; }
        public SelectList GrantedRoles { get; set; }
    }
}

CadetCorps/Areas/SecurityGuard/ViewModels/GrantRolesToUserViewModel.cs
using System.Web.Mvc;
using System.Web.Security;

namespace CadetCorps.Areas.SecurityGuard.ViewModels
{
    public class GrantRolesToUserViewModel
    {
        public MembershipUser User { get; set; }
        public string UserName { get; set; }
        public SelectList AvailableRoles { get; set; }
        public SelectList GrantedRoles { get; set; }
    }
}

CadetCorps/Areas/SecurityGuard/Controllers/MembershipController.cs
using System;
using System.Web.Mvc;
using System.Web.Security;
using CadetCorps.Areas.SecurityGuard.ViewModels;
using routeHelpers = SecurityGuard.Core.RouteHelpers;
using SecurityGuard.Core.Attributes;
using CadetCorps.Controllers;
using SecurityGuard.Core.Extensions;
using SecurityGuard.Interfaces;
using SecurityGuard.Services;

namespace CadetCorps.Areas.SecurityGuard.Controllers
{
    [Authorize(Roles = "SecurityGuard")]
    public partial class MembershipController : BaseController
    {

        #region ctors

        private readonly IMembershipService _membershipService;
        private readonly IRoleService _roleService;

        public MembershipController()
        {
            _roleService = new RoleService(Roles.Provider);
            _membershipService = new MembershipService(Membership.Provider);
        }

        #endregion

        #region Index Method
        public virtual ActionResult Index(string filterby, string searchterm)
        {
            var viewModel = new ManageUsersViewModel();
            viewModel.Users = null;
            viewModel.FilterBy = filterby;
            viewModel.SearchTerm = searchterm;

            int totalRecords;
            int page = Convert.ToInt32(Request["page"]);
            int pageSize = Convert.ToInt32(Request["pagesize"]);
            if (pageSize == 0)
                pageSize = 25;

            viewModel.PageSize = pageSize;

            if (!string.IsNullOrEmpty(filterby))
            {
                if (filterby == "all")
                {
                    viewModel.PaginatedUserList = _membershipService.GetAllUsers(page, pageSize, out totalRecords).ToPaginatedList(page, pageSize, totalRecords, searchterm, filterby);
                }
                else if (!string.IsNullOrEmpty(searchterm))
                {
                    string query = searchterm + "%";
                    if (filterby == "email")
                    {
                        viewModel.PaginatedUserList = _membershipService.FindUsersByEmail(query, page, pageSize, out totalRecords).ToPaginatedList(page, pageSize, totalRecords, searchterm, filterby);
                    }
                    else if (filterby == "username")
                    {
                        viewModel.PaginatedUserList = _membershipService.FindUsersByName(query, page, pageSize, out totalRecords).ToPaginatedList(page, pageSize, totalRecords, searchterm, filterby);
                    }
                }
            }

            return View(viewModel);
        }
        #endregion

        #region Create User Methods

        public virtual ActionResult CreateUser()
        {
            var model = new RegisterViewModel()
            {
                RequireSecretQuestionAndAnswer = _membershipService.RequiresQuestionAndAnswer
            };
            return View(model);
        }

        /// <summary>
        /// This method redirects to the GrantRolesToUser method.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public virtual ActionResult CreateUser(RegisterViewModel model)
        {
            MembershipUser user;
            MembershipCreateStatus status;
            user = _membershipService.CreateUser(model.UserName, model.Password, model.Email, model.SecretQuestion, model.SecretAnswer, model.Approve, out status);

            return routeHelpers.Actions.GrantRolesToUser(user.UserName);
        }

        /// <summary>
        /// An Ajax method to check if a username is unique.
        /// </summary>
        /// <param name="userName"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CheckForUniqueUser(string userName)
        {
            MembershipUser user = _membershipService.GetUser(userName);
            JsonResponse response = new JsonResponse();
            response.Exists = (user == null) ? false : true;

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Delete User Methods

        [HttpPost]
        [MultiButtonFormSubmit(ActionName = "UpdateDeleteCancel", SubmitButton = "DeleteUser")]
        public ActionResult DeleteUser(string UserName)
        {
            if (string.IsNullOrEmpty(UserName))
            {
                throw new ArgumentNullException("userName");
            }

            try
            {
                _membershipService.DeleteUser(UserName);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "There was an error deleting this user. - " + ex.Message;
            }

            return RedirectToAction("Update", new { userName = UserName });
        }



        #endregion

        #region View User Details Methods

        [HttpGet]
        public ActionResult Update(string userName)
        {
            MembershipUser user = _membershipService.GetUser(userName);

            UserViewModel viewModel = new UserViewModel();
            viewModel.User = user;
            viewModel.RequiresSecretQuestionAndAnswer = _membershipService.RequiresQuestionAndAnswer;
            viewModel.Roles = _roleService.GetRolesForUser(userName);

            return View(viewModel);
        }

        [HttpPost]
        //[ActionName("Update")]
        [MultiButtonFormSubmit(ActionName = "UpdateDeleteCancel", SubmitButton = "UpdateUser")]
        public ActionResult UpdateUser(string UserName)
        {
            if (string.IsNullOrEmpty(UserName))
            {
                throw new ArgumentNullException("userName");
            }

            MembershipUser user = _membershipService.GetUser(UserName);

            try
            {
                user.Comment = Request["User.Comment"];
                user.Email = Request["User.Email"];

                _membershipService.UpdateUser(user);
                TempData["SuccessMessage"] = "The user was updated successfully!";

            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "There was an error updating this user.";
            }

            return RedirectToAction("Update", new { userName = user.UserName });
        }


        #region Ajax methods for Updating the user

        [HttpPost]
        public ActionResult Unlock(string userName)
        {
            JsonResponse response = new JsonResponse();

            MembershipUser user = _membershipService.GetUser(userName);

            try
            {
                user.UnlockUser();
                response.Success = true;
                response.Message = "User unlocked successfully!";
                response.Locked = false;
                response.LockedStatus = (response.Locked) ? "Locked" : "Unlocked";
            }
            catch (Exception)
            {
                response.Success = false;
                response.Message = "User unlocked failed.";
            }

            return Json(response);
        }

        [HttpPost]
        public ActionResult ApproveDeny(string userName)
        {
            JsonResponse response = new JsonResponse();

            MembershipUser user = _membershipService.GetUser(userName);

            try
            {
                user.IsApproved = !user.IsApproved;
                _membershipService.UpdateUser(user);

                string approvedMsg = (user.IsApproved) ? "Approved" : "Denied";

                response.Success = true;
                response.Message = "User " + approvedMsg + " successfully!";
                response.Approved = user.IsApproved;
                response.ApprovedStatus = (user.IsApproved) ? "Approved" : "Not approved";
            }
            catch (Exception)
            {
                response.Success = false;
                response.Message = "User unlocked failed.";
            }

            return Json(response);
        }

        #endregion

        #endregion

        #region Cancel User Methods

        [HttpPost]
        [MultiButtonFormSubmit(ActionName = "UpdateDeleteCancel", SubmitButton = "UserCancel")]
        public ActionResult Cancel()
        {
            return RedirectToAction("Index");
        }

        #endregion



        #region Grant Users with Roles Methods

        /// <summary>
        /// Return two lists:
        ///   1)  a list of Roles not granted to the user
        ///   2)  a list of Roles granted to the user
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        public virtual ActionResult GrantRolesToUser(string username)
        {
            if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index");
            }

            GrantRolesToUserViewModel model = new GrantRolesToUserViewModel();
            model.UserName = username;
            model.AvailableRoles = (string.IsNullOrEmpty(username) ? new SelectList(_roleService.GetAllRoles()) : new SelectList(_roleService.AvailableRolesForUser(username)));
            model.GrantedRoles = (string.IsNullOrEmpty(username) ? new SelectList(new string[] { }) : new SelectList(_roleService.GetRolesForUser(username)));

            return View(model);
        }

        /// <summary>
        /// Grant the selected roles to the user.
        /// </summary>
        /// <param name="userName"></param>
        /// <param name="roleNames"></param>
        /// <returns></returns>
        [HttpPost]
        public virtual ActionResult GrantRolesToUser(string userName, string roles)
        {
            JsonResponse response = new JsonResponse();

            if (string.IsNullOrEmpty(userName))
            {
                response.Success = false;
                response.Message = "The userName is missing.";
                return Json(response);
            }

            string[] roleNames = roles.Substring(0, roles.Length - 1).Split(',');

CadetCorps/Areas/SecurityGuard/Views/Membership/CreateUser.cshtml
@model CadetCorps.Areas.SecurityGuard.ViewModels.RegisterViewModel

@{
    ViewBag.Title = "CreateUser";
    Layout = "~/Areas/SecurityGuard/Views/Shared/_SecurityGuardLayoutPage.cshtml";
}

<div id="breadcrumb">
    @Html.ActionLink("Dashboard", "Index", "Dashboard") > 
    @Html.ActionLink("Manage Users", "Index", "Membership") > 
    Create User
</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<h2>Create User</h2>

<ul>
    <li>To be a minimum of @Membership.MinRequiredPasswordLength characters in length.</li>
    @if (Membership.MinRequiredNonAlphanumericCharacters > 0)
    {
        <li>To have a minimum of @Membership.MinRequiredNonAlphanumericCharacters non-alpha numeric characters included, such as &quot;<span style="font-family: Courier New; font-size: 16px;">(){}-_*&^%$#@@!</span>&quot;.</li>
    }
</ul>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Enter User Credentials</legend>

        <div class="row">
            <label>@Html.LabelFor(model => model.UserName)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.TextBoxFor(model => model.UserName, new { @class = "text" })</span>
                <span class="system negative" id="username-message">@Html.ValidationMessageFor(model => model.UserName)</span>
            </div>
        </div>

        <div class="row">
            <label>@Html.LabelFor(model => model.Email)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.TextBoxFor(model => model.Email, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.Email)</span>
            </div>
        </div>

        <div class="row">
            <label>@Html.LabelFor(model => model.Password)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.PasswordFor(model => model.Password, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.Password)</span>
            </div>
        </div>

        <div class="row">
            <label>@Html.LabelFor(model => model.ConfirmPassword)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.PasswordFor(model => model.ConfirmPassword, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.ConfirmPassword)</span>
            </div>
        </div>

        @if (Model.RequireSecretQuestionAndAnswer)
        {
        <div class="row">
            <label>@Html.LabelFor(model => model.SecretQuestion)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.TextBoxFor(model => model.SecretQuestion, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.SecretQuestion)</span>
            </div>
        </div>

        <div class="row">
            <label>@Html.LabelFor(model => model.SecretAnswer)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.TextBoxFor(model => model.SecretAnswer, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.SecretAnswer)</span>
            </div>
        </div>
        }

        <div class="row">
            <label>@Html.LabelFor(model => model.Approve)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.EditorFor(model => model.Approve, new { @class = "text" })</span>
                <span class="system">@Html.ValidationMessageFor(model => model.Approve)</span>
            </div>
        </div>


        @Html.HiddenFor(model => model.RequireSecretQuestionAndAnswer)
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to Manage Users", "Index")
</div>


<script type="text/javascript">

    $(function () {

        var msg = $("#username-message");
        var btn = $("input[type='submit']");

        $("#UserName").focus();

        $("#UserName").blur(function () {

            var username = $(this).val();

            if (username.length == 0) {
                alert("No username.");
                return;
            }

            $.ajax({
                url: '@Url.Action("CheckForUniqueUser", "Membership")',
                dataType: 'json',
                type: 'GET',
                data: { userName: username },
                success: OnCheckForUniqueUserSuccess,
                error: OnCheckForUniqueUserError
            });
        });

        function OnCheckForUniqueUserSuccess(data) {
            if (data.Exists) {
                msg.text("This username already exists.  Please enter a new one.");
                btn.attr("disabled", "disabled");
            } else {
                msg.text("");
                btn.removeAttr("disabled");
            }
        }

        function OnCheckForUniqueUserError(xhr, status, error) {
            msg.text("There was an error checking uniqueness.");
        }
    });

</script>

CadetCorps/Areas/SecurityGuard/Views/Membership/GrantRolesToUser.cshtml
@model CadetCorps.Areas.SecurityGuard.ViewModels.GrantRolesToUserViewModel
@{
    ViewBag.Title = "GrantRolesToUser";
    Layout = "~/Areas/SecurityGuard/Views/Shared/_SecurityGuardLayoutPage.cshtml";
}

<div id="breadcrumb">
    @Html.ActionLink("Dashboard", "Index", "Dashboard") > 
    @Html.ActionLink("Manage Users", "Index", "Membership") > 
    Grant Roles To User
</div>

<h2>
    Grant Roles To User</h2>
<p>
    Clicking the &quot;Grant&quot; or &quot;Revoke&quot; buttons will execute that command.</p>
<p>
    Grant any of the following roles to: <span id="username-to-grant-roles">@Model.UserName</span></p>

<ul class="system_messages" style="display: none;">
    <li><span class="ico"></span><strong class="system_title"></strong></li>
</ul>

<fieldset style="float: left; height: 300px;">
    <div id="available-roles">
        <h3>
            Available roles</h3>
        @Html.ListBox("AvailableRoles", Model.AvailableRoles)
    </div>
    <div id="grant-controls">
        <button id="grant-button">
            Grant --&gt;</button><br />
        <button id="revoke-button">
            &lt;-- Revoke</button>
    </div>
    <div id="granted-roles">
        <h3>
            Granted Roles</h3>
        @Html.ListBox("GrantedRoles", Model.GrantedRoles)
    </div>
</fieldset>
<div style="clear:both;"></div>

<script type="text/javascript">
    $(function () {

        var message = $(".system_messages");

        /******************************************************
        * Begin Grant/Revoke commands
        ******************************************************/
        var availableList = $("#AvailableRoles");
        var grantedList = $("#GrantedRoles");

        $("#grant-button").click(function () {
            // First check if any items in the available list
            // are selected.
            if (availableList.val() == null) {
                alert("You must select a role to grant.");
                return;
            }

            // Then move the selected list items to the 
            // granted roles list.
            move_list_items("AvailableRoles", "GrantedRoles");

            // Now take all the roles from the granted list
            // and create a single comma-delimited list.
            var grantedRoles = "";
            $.each(grantedList.val(), function (index, data) {
                grantedRoles += data + ",";
            });

            // Now execute the command using jQuery ajax.
            $.ajax({
                url: '@Url.Action("GrantRolesToUser", "Membership")',
                dataType: 'json',
                type: 'POST',
                data: { userName: '@Model.UserName', roles: grantedRoles },
                success: OnGrantedSuccess,
                error: OnGrantedError
            });
        });

        function OnGrantedSuccess(data) {
            message.show().delay(5000).fadeOut();    // Show the message
            $("li", message).addClass("green");      // Apply the Green style
            $("strong", message).text(data.Message); // Insert the message
        }

        function OnGrantedError(xhr, status, error) {
            alert(error);
        }



        $("#revoke-button").click(function () {
            // First make sure at least one role in the 
            // granted list is selected to revoke.
            if (grantedList.val() == null) {
                alert("You must select a role to revoke.");
                return;
            }

            // Now move the item back to the Available list.
            move_list_items("GrantedRoles", "AvailableRoles");

            // Now make a comma-delimited string of revoked items.
            var revokedRoles = "";
            $.each(availableList.val(), function (index, data) {
                revokedRoles += data + ",";
            });

            // Now execute the command using jQuery ajax.
            $.ajax({
                url: '@Url.Action("RevokeRolesForUser", "Membership")',
                dataType: 'json',
                type: 'POST',
                data: { userName: '@Model.UserName', roles: revokedRoles },
                success: OnRevokedSuccess,
                error: OnRevokedError
            });
        });

        function OnRevokedSuccess(data) {
            message.show().delay(5000).fadeOut();
            $("li", message).addClass("green");
            $("strong", message).text(data.Message);
        }

        function OnRevokedError(xhr, status, error) {
            alert(error);
        }

        // This function moves items from one list to the other.
        function move_list_items(sourceid, destinationid) {
            $("#" + sourceid + "  option:selected").appendTo("#" + destinationid);
        }
        /******************************************************
        * End Grant/Revoke commands
        ******************************************************/



    });
</script>

CadetCorps/Areas/SecurityGuard/Views/Membership/Update.cshtml
@model CadetCorps.Areas.SecurityGuard.ViewModels.UserViewModel
@{
    ViewBag.Title = "UserDetails";
    Layout = "~/Areas/SecurityGuard/Views/Shared/_SecurityGuardLayoutPage.cshtml";
}
<div id="breadcrumb">
    @Html.ActionLink("Dashboard", "Index", "Dashboard") >
    @Html.ActionLink("Manage Users", "Index", "Membership") > User Details
</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<h2>
    User Details</h2>
@{
    if (TempData.Keys.Contains("SuccessMessage"))
    {
    <ul class="system_messages">
        <li class="green"><span class="ico"></span><strong class="system_title">@TempData["SuccessMessage"]</strong></li>
    </ul>

    }
    else if (TempData.Keys.Contains("ErrorMessage"))
    {
    <ul class="system_messages">
        <li class="red"><span class="ico"></span><strong class="system_title">@TempData["ErrorMessage"]</strong></li>
    </ul>
        
    }
}
@using (Html.BeginForm("UpdateDeleteCancel", "Membership", new { userName = @Model.User.UserName }, FormMethod.Post, new { id = "user-form" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="row">
            <label>@Html.LabelFor(model => model.User.UserName)</label>
            <div class="inputs">
                <span class="input_wrapper">@Model.User.UserName</span>
            </div>
        </div>
        <div class="row">
            <label>@Html.LabelFor(model => model.User.Email)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.TextBoxFor(model => model.User.Email, new { @class = "text" })</span>
                <span class="system">@Html.ValidationMessageFor(model => model.User.Email)</span>
            </div>
        </div>
        <div class="row">
            <label>@Html.LabelFor(model => model.User.Comment)</label>
            <div class="inputs">
                <span class="input_wrapper textarea_wrapper">
                    @Html.TextAreaFor(model => model.User.Comment, new { @class = "text" })
                </span><span class="system">@Html.ValidationMessageFor(model => model.User.Comment)</span>
            </div>
        </div>
        <div class="row">
            <label>@Html.LabelFor(model => model.User.IsApproved, "Is Approved")</label>
            <div class="inputs">
                <span class="input_wrapper">
                    @{
    string btnLblApprove = "";
    string cssClass = "";
    if (Model.User.IsApproved)
    {
        btnLblApprove = "Deny";
        cssClass = "positive";
    }
    else
    {
        btnLblApprove = "Approve";
        cssClass = "negative";
    }
                        <text><span id="approve-deny-div" class="system @cssClass">@(Model.User.IsApproved ? "Approved" : "Not Approved")</span></text>
                        <text>&nbsp;- <a id="btn-approve" href="#">@btnLblApprove</a></text>
                    }
                </span><span class="system" id="approve-message"></span>
            </div>
        </div>
        <div class="row">
            <label>@Html.LabelFor(model => model.User.IsLockedOut, "Is Locked Out")</label>
            <div class="inputs">
                <span class="input_wrapper">
                    @{
                    
    if (Model.User.IsLockedOut)
    {
        cssClass = "negative";
    }
    else
    {
        cssClass = "positive";
    }
                        <text><span id="locked-unlocked-div" class="system @cssClass">@(Model.User.IsLockedOut ? "Locked" : "Unlocked")</span> </text>
                        if (Model.User.IsLockedOut)
                        { 
                            <span id="unlock-span">&nbsp;- <a id="btn-lock" href="#">Unlock</a></span>    
                        }
                    }
                </span><span class="system" id="lock-message"></span>
            </div>
        </div>
        <div class="row">
            <label>@Html.LabelFor(model => model.User.IsOnline, "Is Online")</label>
            <div class="inputs">
                <span class="input_wrapper">
                    @{
    if (Model.User.IsOnline)
    {
                        <text>Online</text>
    }
    else
    {
                        <text>Off-line</text>
    }
                    }
                </span>
            </div>
        </div>
        <div class="row">
            <label>@Html.LabelFor(model => model.User.LastActivityDate, "Last Activity Date")</label>
            <div class="inputs">
                <span class="input_wrapper">@Model.User.LastActivityDate</span>
            </div>
        </div>
        <div class="row">
            <label>@Html.LabelFor(model => model.User.LastLockoutDate, "Last Lockout Date")</label>
            <div class="inputs">
                <span class="input_wrapper">@Model.User.LastLockoutDate</span>
            </div>
        </div>
        <div class="row">
            <label>@Html.LabelFor(model => model.User.LastLoginDate, "Last Login Date")</label>
            <div class="inputs">
                <span class="input_wrapper">@Model.User.LastLoginDate</span>
            </div>
        </div>
        <div class="row">
            <label>
                Last Password
                <br />
                Changed Date</label>
            <div class="inputs">
                <span class="input_wrapper">@Model.User.LastPasswordChangedDate</span>
            </div>
        </div>
        @if (@Model.RequiresSecretQuestionAndAnswer)
        {
            <div class="row">
                <label>@Html.LabelFor(model => model.User.PasswordQuestion, "Password Question")</label>
                <div class="inputs">
                    <span class="input_wrapper">@Model.User.PasswordQuestion</span>
                </div>
            </div>
        }
        <fieldset>
            <legend>Roles for @Model.User.UserName (@Html.ActionLink("Edit", "GrantRolesToUser", "Membership", new { userName = @Model.User.UserName }, null))</legend>
            <ul>
                @foreach (var role in @Model.Roles)
                {
                    <li>@role</li>
                }
            </ul>
        </fieldset>
        @Html.HiddenFor(model => model.User.UserName)
        @Html.HiddenFor(model => model.User.ProviderUserKey)
        <p style="text-align: right;">
            <input type="submit" value="Cancel" name="UserCancel" />&nbsp;
            <input type="submit" value="Delete" name="DeleteUser" id="DeleteUser" />&nbsp;
            <input type="submit" value="Update" name="UpdateUser" />&nbsp;
        </p>
    </fieldset>
    
}
<script type="text/javascript">

    $(function () {


        $("#DeleteUser").click(function () {
            if (confirm("Are you sure you want to delete this user?  This will delete the user and any granted roles.")) {
                return true;
            } else {
                return false;
            }
        });



        /*****************************************************
        * Begin Approve/Deny functions
        *****************************************************/
        var approveMsg = $("#approve-message");
        $("#btn-approve").click(function () {
            var userName = $("#User_UserName");

            $.ajax({
                url: '@Url.Action("ApproveDeny", "Membership")',
                dataType: 'json',
                type: 'POST',
                data: { userName: userName.val() },
                success: OnApproveDenySuccess,
                error: OnApproveDenyError
            });
        });

        function OnApproveDenySuccess(data) {
            if (data.Success) {
                approveMsg.text(data.Message).addClass("positive").show().delay(3000).fadeOut();
                if (data.Approved) {
                    $("#btn-approve").text("Deny");
                    $("#approve-deny-div").text("Approved").addClass("system").addClass("positive").removeClass("negative");
                } else {
                    $("#btn-approve").text("Approve");
                    $("#approve-deny-div").text("Not Approved").addClass("system").addClass("negative").removeClass("positive");
                }
                $("span .approved-notice").text(data.ApprovedStatus);

            } else {
                approveMsg.text(data.Message).addClass("negative").delay(5000).fadeOut();
            }
        }

        function OnApproveDenyError(xhr, status, error) {
            approveMsg.text(error).addClass("negative").delay(5000).fadeOut();
        }

        /*****************************************************
        * End Approve/Deny functions
        *****************************************************/






        /*****************************************************
        * Begin Unlock functions
        *****************************************************/

        var lockMsg = $("#lock-message");

        $("#btn-lock").click(function () {
            var userName = $("#User_UserName");

            $.ajax({
                url: '@Url.Action("Unlock", "Membership")',
                dataType: 'json',
                type: 'POST',
                data: { userName: userName.val() },
                success: OnUnlockSuccess,
                error: OnUnlockError
            });
        });

        function OnUnlockSuccess(data) {
            if (data.Success) {
                lockMsg.text(data.Message).addClass("positive").show().delay(3000).fadeOut();
                if (data.Locked) {
                    $("#locked-unlocked-div").text(data.LockedStatus).removeClass("positive").addClass("negative");
                } else {
                    $("#unlock-span").hide();
                    $("#locked-unlocked-div").text(data.LockedStatus).removeClass("negative").addClass("positive");
                }
            } else {
                lockMsg.text(data.Message).addClass("negative").delay(5000).fadeOut();
            }
        }

        function OnUnlockError(xhr, status, error) {
            lockMsg.text(error).addClass("negative").delay(5000).fadeOut();
        }

        /*****************************************************
        * End Unlock functions
        *****************************************************/




    });
</script>